using System.Diagnostics;

namespace FFXILauncher.Services;

public class AshitaConfig
{
    /// <summary>Your private server's hostname or IP address.</summary>
    public string ServerHost  { get; set; } = "YOUR-SERVER-IP";

    /// <summary>Full path to the FFXI game folder (e.g. C:\Program Files (x86)\SquareEnix\FINAL FANTASY XI)</summary>
    public string GamePath    { get; set; } = "";

    /// <summary>Name used for the Ashita boot profile (no spaces).</summary>
    public string ProfileName { get; set; } = "myprivateserver";
}

/// <summary>
/// Writes Ashita v4 boot profiles and launches ashita-cli.exe headlessly.
/// Profile format based on Ashita v4 example-privateserver.ini.
/// </summary>
public class AshitaManager
{
    private readonly string _ashitaRoot;

    public AshitaManager(string ashitaRoot)
    {
        _ashitaRoot = ashitaRoot;
    }

    public bool IsAshitaPresent() =>
        File.Exists(Path.Combine(_ashitaRoot, "ashita-cli.exe"));

    /// <summary>
    /// Writes the Ashita v4 boot config INI to config\boot\{ProfileName}.ini.
    /// Returns the full path of the written file.
    /// </summary>
    public string WriteProfile(AshitaConfig config)
    {
        var configDir   = Path.Combine(_ashitaRoot, "config", "boot");
        Directory.CreateDirectory(configDir);

        var profilePath = Path.Combine(configDir, $"{config.ProfileName}.ini");

        // Normalize game path — Ashita wants backslashes, no trailing slash
        var gamePath = config.GamePath.TrimEnd('\\', '/');

        var ini = $"""
            ;---------------------------------------------------------------------------------------------------
            ; Auto-generated by FFXILauncher — do not edit manually.
            ; Regenerated on every launch.
            ;---------------------------------------------------------------------------------------------------

            [ashita.launcher]
            autoclose   = 1
            name        = {config.ProfileName}

            [ashita.boot]
            file        = .\bootloader\pol.exe
            command     = --server {config.ServerHost}
            gamemodule  = ffximain.dll
            script      = default.txt
            args        =

            [ashita.fonts]
            d3d8.disable_scaling = 0
            d3d8.family = Arial
            d3d8.height = 10

            [ashita.input]
            gamepad.allowbackground         = 0
            gamepad.disableenumeration      = 0
            keyboard.blockinput             = 0
            keyboard.blockbindsduringinput  = 1
            keyboard.silentbinds            = 0
            keyboard.windowskeyenabled      = 0
            mouse.blockinput                = 0
            mouse.unhook                    = 1

            [ashita.language]
            playonline  = 2
            ashita      = 2

            [ashita.logging]
            level       = 5
            crashdumps  = 1

            [ashita.misc]
            addons.silent   = 0
            aliases.silent  = 0
            plugins.silent  = 0

            [ashita.polplugins]
            sandbox = 0

            [ashita.resources]
            offsets.use_overrides   = 1
            pointers.use_overrides  = 1
            resources.use_overrides = 1

            [ashita.taskpool]
            threadcount = -1

            [ashita.window.startpos]
            x = -1
            y = -1

            [ffxi.direct3d8]
            presentparams.backbufferformat                  = -1
            presentparams.backbuffercount                   = -1
            presentparams.multisampletype                   = -1
            presentparams.swapeffect                        = -1
            presentparams.enableautodepthstencil            = -1
            presentparams.autodepthstencilformat            = -1
            presentparams.flags                             = -1
            presentparams.fullscreen_refreshrateinhz        = -1
            presentparams.fullscreen_presentationinterval   = -1
            behaviorflags.fpu_preserve                      = 0

            [ffxi.registry]
            0000 = 6
            0001 = 1920
            0002 = 1080
            0003 = 4096
            0004 = 4096
            0005 = -1
            0006 = -1
            0007 = 1
            0008 = -1
            0009 = -1
            0010 = -1
            0011 = 2
            0012 = -1
            0013 = -1
            0014 = -1
            0015 = -1
            0016 = -1
            0017 = 0
            0018 = 2
            0019 = 1
            0020 = 0
            0021 = 1
            0022 = 0
            0023 = 0
            0024 = -1
            0025 = -1
            0026 = -1
            0027 = -1
            0028 = 0
            0029 = 20
            0030 = 0
            0031 = 1002740646
            0032 = 0
            0033 = 0
            0034 = 1
            0035 = 1
            0036 = 2
            0037 = 1920
            0038 = 1080
            0039 = 1
            0040 = 0
            0041 = 0
            0042 = {gamePath}
            0043 = 1
            0044 = 1
            0045 = 0
            """;

        File.WriteAllText(profilePath, ini);
        return profilePath;
    }

    /// <summary>
    /// Launches ashita-cli.exe pointing at the boot profile we just wrote.
    /// </summary>
    public Process Launch(AshitaConfig config)
    {
        var cliPath    = Path.Combine(_ashitaRoot, "ashita-cli.exe");
        // Path relative to Ashita root, as ashita-cli expects
        var profileArg = $"config/boot/{config.ProfileName}.ini";

        var psi = new ProcessStartInfo
        {
            FileName         = cliPath,
            Arguments        = $"\"{profileArg}\"",
            WorkingDirectory = _ashitaRoot,
            UseShellExecute  = true,
        };

        return Process.Start(psi)
               ?? throw new InvalidOperationException("Process.Start returned null.");
    }
}
